### ISSUE TITLE
Usability test: (BUG) Emails are not being sent on account creation.

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#102]
Upon creating any users, emails are not being sent by the system with a link to set their initial password.

**Comment by porta-antiporta** [comment]
This looks to be an intermittent issue.  Looking at SendGrid's console, some emails are going through (and it's not just Joe's users going through, `uskpa-auditor` was me).

However, I have created a few licensees today (no password created) and the emails are not going out.  When I run it locally, mailhog is capturing the emails as being sent 100% of the time.  

Could it be some funky connection error between the app and SendGrid?

**Comment by Jkrzy** [comment]
😦

@porta-antiporta --  I haven't been able to replicate this, and a connection error between the app and SendGrid when attempting to queue the outgoing email for delivery _should_ raise a 500 server error if it fails. 

Let's find some time to pair and try to replicate this with eyes-on.
