### ISSUE TITLE
As an admin, I need to be able to create a receipt when I register certificates

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#132]
After an admin registers certificates, they need to provide a receipt that is printed that the contact signs.  This receipt contains information gathered during the transaction or is generated by the system.

- [x] Receipt/Transaction number (long integer. Can seed starting number with last in legacy system -or- choose date/time based receipt numbering)
- [x] Licensee Name
- [x] Licensee Address
- [x] Individually enumerated KPC numbers (includes the `US`)
- [x] Total paid
- [x] Total # of certificates
- [x] Unit price of certificate
- [x] Payment method
- [x] Contact
- [x] Date sold

This information is printed in a layout where the contact purchasing the licensees can sign.  See attached template .pdf.  We need not follow the exact formatting, but we do need the same content (i.e. words).

This document will be accessible on the screen following certificate registration.

Further 
- [x] list individual transactions can be accessed in the admin screen.  
    - [x] Note, this screen need not render the receipt again; but it can if it's a low lift.  Keep in mind `unit price` is something that could change after. So unless we store the unit price with each transaction....
    - [x] The key things to track for a transaction is the value of the fields on the register certificate screen.
    - [x] List is ordered by Receipt (transaction) number.
- [x] Replace `Cecilia Gardner` with `Martin Hochbaum` on the payment instructions.  Judgement call on whether name/address of payment instructions is configurable via admin screen or a code change.

Current template: 
[Receipt-Template.pdf](https://github.com/USKPA-dev/uskpa/files/2019137/Receipt-Template.pdf)

**Comment by porta-antiporta** [comment]
Added requirement:
- [ ] Change Cecilia's name to Martin on receipt (Martin Hochbaum)

**Comment by jastrowinkle** [comment]
Jastro Winkle Diamond Co
Diamond Producers of America
To replace USKPA Org
