### ISSUE TITLE
Enhanced logging

### ISSUE THREAD

**Issue by Jkrzy** [USKPA-dev/uskpa#139]
While a full ATO, and the associated substantial logging, is not required, additional logging would assist debugging should any issues arise.

Let's log!

- [ ] All errors (currently emailed, log to console as well so captured by heroku)
- [ ] Login
- [ ] Logout
- [ ] Failed Logins
- [ ] Certificate status changes
- [ ] When an admin makes an edit via the admin panel
- [ ]  ...

**Comment by porta-antiporta** [comment]
@Jkrzy added a few edits.  Realizing I added those to pave the way for email notifications (to be implemented by whoever maintains this site)...

**Comment by Jkrzy** [comment]
Thanks @porta-antiporta!

Added certificate status changes to logging output. Django automatically logs changes made via the admin interface to the database in the `django_admin_log` table, no need to log it to heroku as well.
