### ISSUE TITLE
Production release

### ISSUE THREAD

**Issue by Jkrzy** [USKPA-dev/uskpa#145]
# Tracking required actions for stand-up of production instance.

## Pre-release

Can be performed any time ahead of release.

Heroku:
- [x] Create production app
- [x] Provision Hobby dyno and Postgres Standard 0 database
- [x] Link to github repository for automated deploys from *master*
- [x] Deploy application per https://github.com/USKPA-dev/uskpa/blob/master/docs/deploy.md

*A few days before go live*
- [x] @porta-antiporta Send email to users communicating schedule and expectations for go live
- [x] @porta-antiporta Configure *Country of Origin* *Void Reasons* in production site

## Release

*Day of go live*
9:30 AM 
- [x] @porta-antiporta Send email to users 1 hr before go live confirming site will go down
 
10:30 AM 
- [x] Solomon to disable site or disable all logins to uskpa.org (so data cannot be changed)
- [x] Solomon to redirect `uskpa.org` to new site
    - [x] Configure domain with production app -- https://devcenter.heroku.com/articles/custom-domains
- [x] Solomon to generate .csv dump of legacy uskpa.org site and send files to @Jkrzy 
- [x] @Jkrzy to run database migration script for only **initial data** and **licensees** and let @porta-antiporta know when it is done
- [x] @porta-antiporta to create licensee and auditor accounts and let Solomon know when complete
- [x] Solomon to double check accounts of licensees and let @Jkrzy know when it checks out
- [x] @Jkrzy to run database migration script for **certificates** and let Solomon and @porta-antiporta know when it is done
- [x] @jkrzy Solomon @porta-antiporta perform spot check of new site

~12:00 PM
- [x] @porta-antiporta to send email to licensees informing them the switch has been completed

## Revert (if needed)
Should any critical issues arise during the window that cannot be immediately resolved
- [ ] Solomon to re-enable legacy uskpa.org site
- [ ] Solomon to flip uskpa.org to point back to legacy site
- [ ] @porta-antiporta send out email informing licensees/users/stakeholders

**Comment by porta-antiporta** [comment]
Need to merge #162 into this one.

**Comment by porta-antiporta** [comment]
Didn't realize this existed already

**Comment by porta-antiporta** [comment]
@Jkrzy pls take a peek and see if there's anything that seems off here.

**Comment by Jkrzy** [comment]
@porta-antiporta Looks great!

For the `void reasons` If you have that list now -- we can include it in the `initial_data` load. 

If desired, I'm happy to do a run through of this process prior to the release.

**Comment by porta-antiporta** [comment]
**WE ARE LIVE** :shipit: :rocket: :ship:
