### ISSUE TITLE
Set or remove contact display for certificates

### ISSUE THREAD

**Issue by Jkrzy** [USKPA-dev/uskpa#160]
Certificate details page currently renders a `Contact:` line item which is blank for every cert. 

The original intention was to display the `user` who purchased the certificate here. 

Need to determine if that is still desirable and:

If yes, add a contact field to the certificate model and populate it on Certificate registration
If no, remove contact from the certificate details template

**Comment by porta-antiporta** [comment]
Let's remove it.  Admin can see this via History table already.

**Comment by Jkrzy** [comment]
@porta-antiporta , Taking this opportunity to tweak a few other fields here:

Modified: This is the date a certificate was last modified in the database, not useful for users. Removing

Assignor: This is the admin user who generated the certificate, not useful for users. Removing

Notes: This is the reason a certificate was voided, duplicate display when present as we're rendering that as a banner on the page when present.  Removing.

**Comment by porta-antiporta** [comment]
@Jkrzy so `last_modified` in the UI is not tied to the removed `modified` field?

**Comment by Jkrzy** [comment]
@porta-antiporta `last_modified` is the name of the database field, it still exists and is tracked. `Modified` is the label we gave on the Certificate details page to display that information. We're just removing the display of that info on the details page, its still tracked in the database and visible in the admin interface.

**Comment by porta-antiporta** [comment]
:thumbsup:
