### ISSUE TITLE
Handle certificates with no associated licensee

### ISSUE THREAD

**Issue by Jkrzy** [USKPA-dev/uskpa#161]
W/ current legacy data migration there are 51 records with no associated licensee. 

Need to assess if these are TEST records which should _excluded_ from production database or another issue.

As part of this issue -- Update certificate details template to display an empty string as opposed to `None` for empty Certificate fields. 

Missing licensees:
```
13434, 13435, 13436, 13437, 13438, 13439, 13440, 13441, 13442, 13443, 13444, 13445, 25915, 25916, 25917, 25918, 25919, 25920, 25921, 25922, 25923, 25924, 25925, 25926, 25927, 25928, 25929, 25930, 25931, 25932, 25933, 25934, 21955, 24539, 26613, 26614, 26615, 26616, 26617, 26618, 26619, 26620, 26621, 26622, 26623, 26624, 26625, 26626, 27666, 2342323, 28571
```

**Comment by porta-antiporta** [comment]
For any certs related to licensee #34 - do not import (as they are all test licensees)
For any certs related to licensee 23 - associate to a Licensee we'll name `Orphan`

**Comment by porta-antiporta** [comment]
Per :slack: convo, to simplify
For any certs related to licensee 23 - set Licensee to NULL
Admin at a later time can associate this field if they ever create what licensee 23 was in the legacy system.
