### ISSUE TITLE
As a Licensee, when I log in, I am shown the KP certificates assigned to the licensee I am associated to

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#17]
This story basically implements the landing experience for a licensee once they log in.

* Licensee logs in.
* Licensee automatically sees a list of certificates associated to their org
* From the list the user is able to get to #18 

This story is just to bootstrap the entry to being able to fill out a certificate, so don't spend too much time on the grid view.

**Comment by porta-antiporta** [comment]
@Jkrzy One thing I didn't explictly call out, but hope was already taken into consideration.

A licensee user can **only** see the certificates that have been assigned to their associated licensee org.

**Comment by Jkrzy** [comment]
Fulfilled in 8b8f977d083ef606079efe747eb72f9fc0fc871d. Non admin users are only shown certificates assigned to licensees for which they are a contact.
