### ISSUE TITLE
Export is not working in IE

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#183]
When exporting certificate results in IE, a new window is being launched with an error as opposed to downloading the exported file.

**Comment by porta-antiporta** [comment]
Poking around the interwebs and looking at the implementation.  Have a theory.

So it's triggered by opening up a new window wherein it calls the params to export.  However, that URL is longer than what may be the maximum allowed URL for IE (>2083 char)

https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers/417184#417184

Because the URL gets truncated in IE, the actual query to export is then incomplete which is why IE throws a `This page can't be displayed` error.

**Comment by Jkrzy** [comment]
Thanks for digging in @porta-antiporta! That is definitely a factor here.

Made some tweaks to the export functionality in #184  to support IE11 and converting export to a proper anchor tag.

**Comment by porta-antiporta** [comment]
Tested working in both browsers.
