### ISSUE TITLE
As a licensee, I need quick access to my Address book

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#194]
Currently, the only way for a licensee to access their address book is via the Licensee link on an individual certificate details page.  This is not very intuitive.

- [x] If I am a licensee I see an `Address book` nav item
- [x] Clicking on that nav item lands me in the licensee page
- [x] Edge case: If I am associated to more than 1 licensee, I do not see that nav item (this is never going to be a standard config, it's just to ensure we don't crash)

**Comment by Jkrzy** [comment]
- [ ] If I'm associated with no licensees do not display an `Address book`  link
