### ISSUE TITLE
As an admin and auditor, I can see what users are associated to a licensee.

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#22]
As part of #5 there exists a mandatory primary contact field for the licensee. It is currently a free form text which doesn't guarantee a linkage to an actual user in the system.

Further, making it mandatory means users need to be created first then associated to licensee.

Revisiting:
* Remove primary contact field. 
* Replace with an associated users view
  * Likely there will only be 1 user associated to a licensee; at the most a handful.
* The admin can add / remove users associated to licensee.
* This view can be empty (i.e. it's OK if there are no users associated to the licensee)

**Comment by Jkrzy** [comment]
Resolved in #26, Licensee contacts are now editable via the Licensee admin interface.
