### ISSUE TITLE
As a developer, I want to be able to load a set of test data into the website.

### ISSUE THREAD

**Issue by Jkrzy** [USKPA-dev/uskpa#28]
There are currently a few separate sets of fixtures data which can be used to populate a new database.

This data should be expanded to include:

- [ ] Licensees
- [ ] Certificates
  - [ ] varying statuses and licensee associations
  - [ ] including voided certificates
- [ ] Users
  - [ ] varying roles and licensee associations

Developers should be able load this data with a single command, greatly facilitating the stand-up of additional development/review instances with sufficient data to mimic a live system.

**Comment by porta-antiporta** [comment]
@Jkrzy This feels like a "nice to have"?  Inclined to not tackle this as part of the MVP build project.

**Comment by jastrowinkle** [comment]
jkrzy and the rest of the repo group dev's your efforts maylook good on paper but you are where crime and government embrace

**Comment by jastrowinkle** [comment]
Facebook eBay craigslist all use USKPA CERTIFICATE IN BUY SALES GROUP ads you need to correct the code allowing those ads and groups trading in rough diamonds not mined in the u.s. you are complacent in the $20,000,000,000 worth of foreign mined diamonds being exported imported into the state of California yearly.
