### ISSUE TITLE
As a logged in user, I should be automatically logged out of my account after 20 minutes of inactivity.

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#34]
Currently, it seems that the app will keep you logged in indefinitely.

We should log people out after 20 minutes of inactivity.

* User logs in
* User stays idle for 20 minutes
* User attempts to select a screen/field in the app
* User is brought to log in screen
* Discuss during grooming
- After logging in, where do they go?

**Comment by Jkrzy** [comment]
Resolved in #35
