### ISSUE TITLE
As a license, when I log in, I see the filters that are applied to what my view is.

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#36]
In #17 we have implemented a basic list view of the certificates a licensee is associated to.

This story will take that implementation and turn it more into a search paradigm.

Using the following mockup as a reference : https://gsa.invisionapp.com/share/HMGXXJQWUGN#/screens/291545486_Search_Filters 

When licensee logs in they see:

- [x] Certificates they are associated to
- [x] Filtered by certificates that are **NOT** 'Delivered' 'Voided'
- [x] Result set is orderd by Status in Descending order (In-transit, Prepared, Assigned)
   - Note the assumption is that the order in ascending order is (NULL, Assigned, Prepared, In-transit, Delivered, Voided)
- [x] The following columns are visible in the list view
  - Certificate number
  - Status
  - Date of last status update
  - Ultimate consignee Name
  - Value
- [x] The following fields are able to be searched:
- [x] Certificate number
- [x] Current status
- [x] Date certificate was assigned
   - Search by range
- [x] Any field on the physical certificate (see: https://github.com/USKPA-dev/uskpa/wiki/Certificate)
   - Dates - search by range
   - Strings - search by substring (i.e. doesn't have to be exact match, nor does case need to match)
   - Enumerated value - talk to Jeremy how to handle long enumerated lists, for now use a dropdown that has typeahead support (so can only select 1 value)
   - Numerical (Currency, Decimal, Integer) - search by range

**Comment by Jkrzy** [comment]
Basic search functionality pieces in #47. 

TO DO:
Additional functionality included in the mock-up (export, certificate drill-down)

**Comment by porta-antiporta** [comment]
Closing this issue. Opening a new one for being able to search across multiple values for the same field (like say multiple countries).  That is not an MVP need.
