### ISSUE TITLE
As a licensee, from the list view, I can drill down to each individual certificate

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#37]
In #36 we have the list view for a licensee implemented.

This story will implement the ability to drill down into each individual (the blue triangle) which leads to the following screen:

https://gsa.invisionapp.com/share/HMGXXJQWUGN#/screens/291545487

This essentially shows:
- [ ] All physical fields present on the certificate

Slight differences from the invision mockup:
- [ ] Current status next to to the certificate number 
- [ ] History of the certificate (which should show, dates when a certificate was Assigned, Prepared, Shipped, Delivered, Voided.

**Comment by onezerojeremy** [comment]
I love both of @porta-antiporta's changes and will update the mock-up later this week to reflect (but it'll most likely be Friday late)

**Comment by porta-antiporta** [comment]
Deprioritizing from MVP build as we have drill down capabilities.  It puts the user in a different screen as opposed to the mockup.  But given remaining time/budget, that will have to do for the MVP build.

**Comment by porta-antiporta** [comment]
Not needed
