### ISSUE TITLE
Design: Visual styling

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#43]
Currently we have a very bare style, we have focused on functionality.
Need visual design to step in to set visual styling
* Logos
* Color palette
* Navigation

**Comment by porta-antiporta** [comment]
uskpa.org is the current styling (as a reference).
We have relatively free reign as to the design.

https://www.kimberleyprocess.com/ is the global process website.

**Comment by austinhernandez** [comment]
Here are the assets to send to the client. 

The feedback we are looking for is preferential. Which color scheme, fonts do you like best for the layout? The logo needs to go through other approval, but I can get on another call to explain design decisions.

![logo](https://user-images.githubusercontent.com/23194720/39271675-b30e2c7e-48a7-11e8-9ec3-8377aefa4e76.jpg)
![monochrome 1](https://user-images.githubusercontent.com/23194720/39271676-b31f5710-48a7-11e8-858b-456a6b6b1ebb.png)
![monochrome 2](https://user-images.githubusercontent.com/23194720/39271677-b32b081c-48a7-11e8-9e87-0fe8907a307e.png)
![option3](https://user-images.githubusercontent.com/23194720/39271678-b33bf582-48a7-11e8-8924-376d0e983189.png)

**Comment by austinhernandez** [comment]
The PDF of the kick off call [Visual Design kickoff - USKPA.pdf](https://github.com/USKPA-dev/uskpa/files/1948820/Visual.Design.kickoff.-.USKPA.pdf)

**Comment by porta-antiporta** [comment]
[Visual.Design.kickoff.-.USKPA.pdf](https://github.com/USKPA-dev/uskpa/files/1948992/Visual.Design.kickoff.-.USKPA.pdf)
Amended .pdf that updated the concepts to be ones without the graphic

**Comment by porta-antiporta** [comment]
USKPA and Dept of State have approved logo and concept #2
