### ISSUE TITLE
As a licensee or admin, I can move a certificate through the various statuses in a specific order only

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#46]
There are certain statuses a certificate can go through and only specific transitions allowed.

- [ ] Assigned -> Prepared -> In-transit -> Delivered
- [ ] A certificate can be Voided at any time.  But once Voided, it cannot be unvoided by a licensee.
- [ ] Date setting
   - [ ] Assigned : when a certificate is sold
   - [ ] Prepared : when a licensee prepares certificate
   - [ ] Shipped : licensee manually selects this date upon transition (i.e it's not necessarily when they update the status)
   - [ ] Delivered : licensee manually selects this date (i.e it's not necessarily when they update the status)
   - [ ] Voided : when a licensee voids the certificate.
- [ ] Admin can override any date _but_ it must follow the ordering (Assigned -> Prepared -> Shipped -> Delivered)

**Comment by Jkrzy** [comment]
Implemented in #66
