### ISSUE TITLE
As an admin, when registering a certificate, I can select a date from a date picker

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#48]
Currently when selecting a date, the field is a text field that defaults to today's date (with midnight).

This story is requesting:
- [ ] Default date is today (no timestamp)
- [ ] User can change it via a date picker

Note, for other fields that are dates, we should use the same control to select.

**Comment by Jkrzy** [comment]
Will select a datepicker widget for use across the site.

@porta-antiporta  -- As part of this issue, do _any_ of the Certificate fields need to capture time? I suspect not, but would like to confirm.

``date_of_issue``
``date_of_expiry``
``date_of_sale``

**Comment by porta-antiporta** [comment]
@Jkrzy nope, none of the fields need to capture time.

**Comment by porta-antiporta** [comment]
In grooming @Jkrzy mentioned that USWDS research has shown that date pickers are not user friendly and also pose accessibilty issues.

Modified the headline to get to the heart of the user need:  The ability to enter dates easily into the site.

**Comment by porta-antiporta** [comment]
This one is below the line.

**Comment by porta-antiporta** [comment]
Taking this out of the MVP build.

**Comment by porta-antiporta** [comment]
Not needed
