### ISSUE TITLE
As a user, I can export my filter results to a local file.

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#54]
After a user has selected their filters they may want to export the entire result set to a file for later analysis (likely a .csv).

From the results screen provide the ability for the user to export the results to a local file.

Note: For this story, we can export all fields related to the certificate, but there's a future story to allow the user to choose what fields to display (#59) at which point we'd only want to export what's visible.  Discuss if we want to do that story first (though push came to shove, would choose export over #59)

**Comment by porta-antiporta** [comment]
@Jkrzy One thing came to mind:

What is the data model we use to store status and associated dates.  Is it:
1. A separate table status history table that has `status` column and `date` column (of when it went into that status). i.e. 1 certificate maps to multiple rows in that table.
2. Within the certificate table where there's a `current status` column along with separate columns for `Date purchased`, `Date used` etc.  i.e. 1 certificate really has 1 row capturing it all.

If we are using #1, this export would need to _flatten_ out the status history table to render the certificate as a single row in the .csv (or whatever output format we choose).

**Comment by Jkrzy** [comment]
@porta-antiporta, 2 is accurate for the current data model. Should not need any manipulation for certificate listing export.

**Comment by Jkrzy** [comment]
Implemented in #69
