### ISSUE TITLE
As a licensee I can void a certificate at any point in the process

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#55]
This could already be captured as part of #46.

But a licensee can void a certificate at any point in the process.

When they do so:

- [x] They are required to fill out a reason.  This field can be free form as well as have predefined selections
- [x] They are asked to confirm their intent to void
- [ ] Once voided, only an admin can revert (through the admin panel)

**Comment by Jkrzy** [comment]
Implemented in #67
