### ISSUE TITLE
As a licensee, when preparing a certificate, I get a preview of what I entered prior to committing.

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#57]
Given a licensee cannot make modifications to the certificate after they have "used" it, they need the ability to confirm that the information they entered is correct.

In the current application, there is just a simple screen asking the user to verify then confirm submission.

Would it be possible to overlay the information they entered on top of a USKPA certificate image?

**Comment by Jkrzy** [comment]
Initial implementation in #72, some great review comments by @cmc333333 which will be addressed in a follow-up PR.
