### ISSUE TITLE
As an admin, I can search for certificates in the admin panel

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#58]
Today, an admin can search for users in the admin panel.
But when in certificate view, they can only scroll to find their certificate.
This will be a problem when there are 1000's of certificates in the system.

- [ ] Enable admin to search for certificate by number

**Comment by porta-antiporta** [comment]
Bullet 2 may be a moot point seeing an admin can search on the site then use the edit button to get to the specific certificate.

**Comment by Jkrzy** [comment]
Completed in #65
