### ISSUE TITLE
BUG: New password 1 label includes the help text indicating what an accepted password is.

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#86]
* Log in
* Go to profile page
* See screenshot below

**Comment by porta-antiporta** [comment]
![image](https://user-images.githubusercontent.com/16668007/39823299-68bd2316-5372-11e8-9124-11fca8c31558.png)

**Comment by Jkrzy** [comment]
Fixed in #87, help text no longer rendered under form field label.
