### ISSUE TITLE
Performance of certificate list view for Admin/Auditor

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#90]
Currently when going to the certificate list view, the default filters are assigned, prepared, in-transit.  For licensees, this is not going to be a big number of certificates (in production).  However, for admin and auditor, this could number in thousands.

Further, what if the user selects all statuses?

This story is to ensure that the list view continues to be performant even when there are thousands of results.

**Comment by Jkrzy** [comment]
We're only transferring data for the displayed certificate data on the listing page. Current options limit the user to viewing 100 records at a time, its further restricted on the backend to return a max of 500 records at a time.

We shouldn't hit any issues w/ the list view as  the # of certificates rises. We'll keep an eye on this as the legacy data is migrated.

**Comment by porta-antiporta** [comment]
Will perform once we have :green_book: to load migrated data into test site.

**Comment by porta-antiporta** [comment]
@Jkrzy I think with the demos next week we are at a point where we should load the data migration into the test site. that way i can create users associated with the specific licensees and they can play around in there?

**Comment by porta-antiporta** [comment]
Data migrated on test site. Site continues to remain snappy.
* Able to unfilter and display all 11K+ certificates
* Reengaging filter even iContains ones are fast.
* Export all certificates

👍
