### ISSUE TITLE
Usability test : `Filter` button is not intuitive to user

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#96]
Both licensee and auditor took some time to engage the filter.  They both thought that once they hit `Enter` (in particular, for cert number lookup) that the filter would kick in.

Note, while technically we are _filtering_ results as we have initially searched and loaded _all_ certificates the user has access to, the users view the filters as a way to compose a _search_.

Asks:
- [ ] Trigger filtering when
   - [ ] User Enters free text and hits Enter (ex. ` KPC`, `AES`, `Address`
   - [ ] User selects a checkbox (`status`)
   - [ ] Path of least resistance for ranges (i.e. do they need to fill one of min/max or both?)
- [ ] This means that as they enter text and go from field to field, we are constantly updating the filter result
- [ ] Keep the existing Filter button as well

**Comment by porta-antiporta** [comment]
Updated description based off standup discussion.

**Comment by Jkrzy** [comment]
Resolved in #119
